---
# Traefik Docker Deployment (docker_deployment user)
# Run this after system setup

- name: Deploy Traefik Reverse Proxy
  hosts: docker_ops
  gather_facts: true
  become: false

  vars_files:
    - "../inventory/group_vars/all/main.yml"
    - "../../secrets/vault.yml"

  pre_tasks:
    - name: Verify docker_deployment user has access to Traefik directories
      ansible.builtin.stat:
        path: "{{ traefik_root }}"
      register: traefik_root_stat

    - name: Fail if docker_deployment cannot access Traefik directories
      ansible.builtin.fail:
        msg: "docker_deployment user cannot access {{ traefik_root }}. Run setup_traefik_system.yml first."
      when: not traefik_root_stat.stat.exists

  roles:
    - role: deploy_traefik

  post_tasks:
    - name: Display deployment summary
      ansible.builtin.debug:
        msg: |
          Traefik deployment completed successfully!

          {% if traefik_dashboard_enabled %}
          Dashboard: http://{{ ansible_host }}:{{ traefik_dashboard_port }}
          {% else %}
          Dashboard: Disabled (security)
          {% endif %}
          Proxy ports: {{ traefik_web_port }}, {{ traefik_websecure_port }}

          Container name: {{ traefik_container_name }}
