---
# =============================================================================
# GLOBAL VARIABLES - Single source of truth
# =============================================================================
# References vault variables for sensitive data
# Single environment configuration - no production/staging/development
# =============================================================================

# Server Configuration
vps_server_ip: "{{ vault_vps_server_ip }}"

# Initial Deployment User (has root/sudo access)
initial_deployment_user: "{{ vault_initial_deployment_user }}"
initial_deployment_ssh_key: "{{ vault_initial_deployment_ssh_key }}"

# Containers Deployment User (has Docker access)
containers_deployment_user: "{{ vault_containers_deployment_user }}"
containers_deployment_ssh_key: "{{ vault_containers_deployment_ssh_key }}"

# Current deployment user (will be set based on task type)
deployment_user: "{{ containers_deployment_user }}"
deployment_ssh_key: "{{ containers_deployment_ssh_key }}"

# Docker Network Configuration
docker_network_name: "traefik-network"
docker_network_subnet: "172.20.0.0/16"
traefik_network_name: "{{ docker_network_name }}"
traefik_network_subnet: "{{ docker_network_subnet }}"

# Docker Configuration
traefik_version: "{{ lookup('env', 'TRAEFIK_VERSION') | default('latest') }}"
traefik_image: "traefik:latest"
traefik_container_name: "traefik"
traefik_restart_policy: "unless-stopped"
traefik_docker_restart_policy: "{{ traefik_restart_policy }}"

# Port Configuration
traefik_web_port: 80
traefik_websecure_port: 443
traefik_dashboard_port: 8080

# Container Port Mappings
traefik_container_port: "{{ traefik_web_port }}"
traefik_container_web_port: 80
traefik_container_dashboard_port: 8080

# User Configuration - Simplified approach
traefik_user: "traefik"
traefik_group: "traefik"
traefik_user_groups: []
traefik_user_shell: "/usr/sbin/nologin"
traefik_user_create_home: false

# User ID and Group ID (for Docker container)
traefik_uid: "{{ lookup('env', 'TRAEFIK_UID') | default('1000') }}"
traefik_gid: "{{ lookup('env', 'TRAEFIK_GID') | default('1000') }}"

# Simplified Paths - Following team guidelines
traefik_root: "/opt/traefik"
# No need for separate config_dir, dynamic_dir, etc. - everything goes under traefik_root

# Container Paths - Simplified mapping
traefik_container_config_path: "/traefik.yml"
traefik_container_dynamic_path: "/dynamic"
traefik_container_certs_path: "/acme"
traefik_container_logs_path: "/logs"

# File Configuration - Simplified
traefik_config_file: "{{ traefik_root }}/traefik.yml"
traefik_dynamic_config_dir: "{{ traefik_root }}/dynamic"
traefik_dynamic_config_file: "{{ traefik_root }}/dynamic/middlewares.yml"

# Docker Socket
traefik_docker_socket: "/var/run/docker.sock"

# Logging Configuration
traefik_log_path: "{{ traefik_root }}/logs"
traefik_log_level: "{{ lookup('env', 'TRAEFIK_LOG_LEVEL') | default('INFO') }}"
traefik_log_rotation_days: 7
traefik_log_rotation_mode: "0644"

# Logrotate Configuration
traefik_logrotate_config_path: "/etc/logrotate.d/traefik"
traefik_logrotate_owner: "root"
traefik_logrotate_group: "root"
traefik_logrotate_mode: "0644"

# Directory and File Permissions - Updated for docker_deployment access
traefik_dir_mode: "0770"  # Group has write access
traefik_sensitive_dir_mode: "0770"
traefik_config_file_mode: "0660"  # Group has write access

# Security Configuration
traefik_admin_password: "{{ vault_traefik_admin_password }}"
traefik_hsts_seconds: 31536000
traefik_rate_limit_burst: 100
traefik_rate_limit_average: 50
traefik_tls_min_version: "VersionTLS12"
traefik_tls_cipher_suites:
  - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"

# Monitoring Configuration
traefik_prometheus_buckets:
  - 0.1
  - 0.3
  - 1.2
  - 5.0

# Feature Flags (with sensible defaults)
traefik_backup_enabled: "{{ lookup('env', 'TRAEFIK_BACKUP_ENABLED') | default('false') | bool }}"
traefik_monitoring_enabled: "{{ lookup('env', 'TRAEFIK_MONITORING_ENABLED') | default('false') | bool }}"
traefik_dashboard_enabled: "{{ lookup('env', 'TRAEFIK_DASHBOARD_ENABLED') | default('false') | bool }}"
traefik_rate_limiting_enabled: "{{ lookup('env', 'TRAEFIK_RATE_LIMITING_ENABLED') | default('false') | bool }}"

# Conditional Port Configuration
traefik_base_ports:
  - "{{ traefik_container_port }}:{{ traefik_container_web_port }}"
  - "{{ traefik_websecure_port }}:{{ traefik_websecure_port }}"

traefik_dashboard_ports:
  - "{{ traefik_dashboard_port }}:{{ traefik_container_dashboard_port }}"

# Dynamic port configuration based on dashboard setting
traefik_container_ports: "{{ traefik_base_ports + (traefik_dashboard_ports if traefik_dashboard_enabled else []) }}"

# Firewall Configuration
firewall_allowed_ports:
  - 22    # SSH
  - 80    # HTTP
  - 443   # HTTPS
  - 8080  # Dashboard (when enabled)

# Let's Encrypt Configuration - Updated paths
traefik_acme_email: "{{ vault_traefik_acme_email }}"
traefik_acme_staging: "{{ lookup('env', 'TRAEFIK_ACME_STAGING') | default('false') | bool }}"
traefik_acme_storage: "{{ traefik_container_certs_path }}/acme.json"

# Security Updates Configuration
configure_security_updates_email: "{{ vault_configure_security_updates_email }}"
