---
# Configure Traefik settings and files
# Independent configuration that doesn't interfere with existing services

- name: Verify required configuration variables are defined
  ansible.builtin.assert:
    that:
      - traefik_config_file is defined
      - traefik_user is defined
      - traefik_group is defined
      - traefik_config_file_mode is defined
      - traefik_dynamic_config_dir is defined
      - traefik_logrotate_config_path is defined
      - traefik_logrotate_owner is defined
      - traefik_logrotate_group is defined
      - traefik_logrotate_mode is defined
    fail_msg: "Required configuration variables are not defined. Check inventory configuration."
    success_msg: "All required configuration variables are properly defined."

- name: Create Traefik main configuration
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ traefik_config_file }}"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "{{ traefik_config_file_mode }}"
  tags: [configure, traefik]

- name: Create Traefik dynamic configuration
  ansible.builtin.template:
    src: dynamic.yml.j2
    dest: "{{ traefik_dynamic_config_dir }}/dynamic.yml"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "{{ traefik_config_file_mode }}"
  tags: [configure, traefik]

- name: Create Traefik log rotation configuration
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: "{{ traefik_logrotate_config_path }}"
    owner: "{{ traefik_logrotate_owner }}"
    group: "{{ traefik_logrotate_group }}"
    mode: "{{ traefik_logrotate_mode }}"
  tags: [configure, traefik]

- name: Verify configuration files
  ansible.builtin.debug:
    msg: "Traefik configuration files created successfully"
