---
# Configure Traefik settings and files
# Following simplified directory management approach

- name: Verify required configuration variables are defined
  ansible.builtin.assert:
    that:
      - traefik_config_file is defined
      - traefik_user is defined
      - traefik_group is defined
      - traefik_config_file_mode is defined
      - traefik_dynamic_config_dir is defined
      - traefik_dynamic_config_file is defined
    fail_msg: "Required configuration variables are not defined. Check inventory configuration."
    success_msg: "All required configuration variables are properly defined."

- name: Create Traefik main configuration
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ traefik_config_file }}"
    mode: "{{ traefik_config_file_mode }}"
  tags: [configure, traefik]

- name: Create Traefik dynamic configuration
  ansible.builtin.template:
    src: middlewares.yml.j2
    dest: "{{ traefik_dynamic_config_file }}"
    mode: "{{ traefik_config_file_mode }}"
  tags: [configure, traefik]

- name: Verify configuration files
  ansible.builtin.debug:
    msg: "Traefik configuration files created successfully with simplified structure"
