---
# Setup users and directories for Traefik deployment
# Following simplified directory management approach

- name: Verify all required variables are defined
  ansible.builtin.assert:
    that:
      - traefik_container_name is defined
      - traefik_network_name is defined
      - traefik_network_subnet is defined
      - traefik_user is defined
      - traefik_group is defined
      - traefik_root is defined
      - traefik_web_port is defined
      - traefik_websecure_port is defined
      - traefik_dashboard_port is defined
      - traefik_container_port is defined
      - traefik_admin_password is defined
      - traefik_acme_email is defined
      - traefik_acme_staging is defined
      - traefik_acme_storage is defined
    fail_msg: "Critical variables are not defined. Deployment cannot proceed. Check inventory configuration."
    success_msg: "All critical variables are properly defined. Proceeding with deployment."

- name: Verify required user variables are defined
  ansible.builtin.assert:
    that:
      - traefik_group is defined
      - traefik_user is defined
      - traefik_user_shell is defined
      - traefik_user_create_home is defined
      - traefik_dir_mode is defined
      - traefik_root is defined
    fail_msg: "Required user variables are not defined. Check inventory configuration."
    success_msg: "All required user variables are properly defined."

- name: Ensure traefik system group
  ansible.builtin.group:
    name: "{{ traefik_group }}"
    system: true
  become: true

- name: Ensure traefik system user
  ansible.builtin.user:
    name: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    system: true
    shell: "{{ traefik_user_shell }}"
    create_home: "{{ traefik_user_create_home }}"
    groups: "{{ traefik_user_groups | default([]) }}"
  become: true

- name: Create Traefik root directory
  ansible.builtin.file:
    path: "{{ traefik_root }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "{{ traefik_dir_mode }}"
  become: true

- name: Create Traefik subdirectories
  ansible.builtin.file:
    path: "{{ traefik_root }}/{{ item }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "{{ traefik_dir_mode }}"
  loop:
    - ""
    - dynamic
    - acme
    - logs
  become: true

- name: Create/secure ACME storage
  ansible.builtin.copy:
    dest: "{{ traefik_root }}/acme/acme.json"
    content: "{}\n"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "0600"
    force: false
  become: true

- name: Verify directory setup
  ansible.builtin.debug:
    msg: "Traefik directories created with proper permissions following simplified structure"
