---
# =============================================================================
# STAGING ENVIRONMENT OVERRIDES
# =============================================================================

# Staging-specific settings
traefik_version_override: "latest"
traefik_backup_enabled: true
traefik_monitoring_enabled: true
traefik_dashboard_enabled: true
traefik_rate_limiting_enabled: true

# Staging ports
traefik_web_port: 8080
traefik_websecure_port: 8443
traefik_dashboard_port: 8080
traefik_container_port: 8080
