---
# =============================================================================
# SIMPLIFIED INVENTORY STRUCTURE
# =============================================================================
# Single source of truth for hosts and groups
# =============================================================================

all:
  hosts:
    vps:
      ansible_host: "{{ vps_server_ip }}"
      ansible_user: "{{ initial_deployment_user }}"  # Use initial user for sudo access
      ansible_ssh_private_key_file: "{{ initial_deployment_ssh_key }}"
      ansible_python_interpreter: "/usr/bin/python3"
  children:
    # Environment groups
    production:
      hosts:
        vps:
    staging:
      hosts:
        vps:
    development:
      hosts:
        vps:
    
    # Service groups
    traefik_servers:
      hosts:
        vps:
